### ISSUE TITLE
Changing "max_ticket_cost" in config.toml to anything other than 1 will cause the sniper to fail.

### ISSUE THREAD

**Issue by Fredd2023** [NixV37/keydrop-battle-sniper#2]
Title is self explanatory. 
Doing it makes the sniper scrape once (with no result), and any later scrape will give the error:
"not enough values to unpack (expected 2, got 1)".
![image](https://github.com/NixV37/keydrop-battle-sniper/assets/133052517/b8f2a541-128e-455c-bfb7-085c73f7550f)

**Comment by Nixitov** [comment]
Make sure to download the last version, I fixed it.

If u still get errors tell me again
