### ISSUE TITLE
Failed to join battle 23136777: b'{"statusCode":401,"message":"Unauthorized"}'

### ISSUE THREAD

**Issue by teodorrdl** [NixV37/keydrop-battle-sniper#5]
Browser up to date, session_id correct

**Comment by Alehig** [comment]
activate use_token, this worked for me

**Comment by teodorrdl** [comment]
i fixed it using token from https://key-drop.com/en/token, thanks

**Comment by Nixitov** [comment]
I may need to check because some ppl is getting this issue, prolly the cloudflare bypass is broken or something. Thanks :)
